### ISSUE TITLE
List of Accessibility groups per department

### ISSUE THREAD

**Issue by shawnthompson** [canada-ca/a11y#30]
## Problem to solve

A place to list all the team across the government and a short description of what they do.

## Intended users

Visitors to the site

## Proposal

To have a section of the site dedicated to promoting the work done in different departments of the Government of Canada.

**Comment by stef-barburou** [comment]
should we post potential content here ?

**Comment by shawnthompson** [comment]
I'd like to organize this better. Not sure yet where to post content.

**Comment by shawnthompson** [comment]
Moved to: https://github.com/gc-da11yn/gc-da11yn.github.io/discussions/13
