### ISSUE TITLE
Maps for HTML

### ISSUE THREAD

**Issue by prushforth** [canada-ca/a11y#32]
I would like to be able to contribute our work on Maps for HTML to this toolkit.   

"Maps for HTML" is the name of a [W3C Community Group](https://www.w3.org/community/maps4html/) which aims to extend HTML to include Web maps.   We have a [gh organization](https://github.com/Maps4HTML) where we do our work, and which has contributors from around the world.  We want browsers to natively incorporate maps and features, through the HTML language.

We have a specific, if not quite finished, proposal for how to include maps in HTML, which is the "[MapML Proposal](https://github.com/Maps4HTML/MapML-Proposal)".

The draft specification for MapML ("Map Markup Language"), is available [here](https://maps4html.github.io/MapML/spec/).  MapML is intended to be an extended subset of HTML, as well as a new media type ("text/mapml").  

The evolving "polyfill" for MapML is available [here](https://github.com/Maps4HTML/Web-Map-Custom-Element), with example pages with the running polyfill over [here](https://geogratis.gc.ca/mapml/).  We have engaged with the a11y community to ensure that we stay on a path towards appropriately specifying, implementing and standardizing maps so that they can be more useful to people with disabilities, but I recognize that this will be a bit of a process.  

There is also an index of various resources available [here](https://maps4html.org/).

We held a global [workshop ](https://www.w3.org/2020/maps/agenda)in September 2020, and many of the presentations and panels were based on what accessibility means for maps, and how it could be improved.  I admit that our polyfill may not be fully accessible at this time, but I would appreciate any and all input on that subject.  My goal in posting here is to get the specifications and polyfill up to a level that they can and should be included in your Digital Accessibility Toolkit.

**Comment by shawnthompson** [comment]
Wow how did I not see this until now? @prushforth we are holding out first meeting on the Digital Accessibility Toolkit this week. I would live to add information here.

**Comment by prushforth** [comment]
OK, let me know what we can do to help!

**Comment by shawnthompson** [comment]
Moved to: https://github.com/gc-da11yn/gc-da11yn.github.io/discussions/12
