### ISSUE TITLE
Bug - access to links on web page but requires login for OneDrive

### ISSUE THREAD

**Issue by MaryBethBaker** [canada-ca/a11y#35]
### Summary

A colleague noticed some broken links on slack and I'm just sharing this information with the team working on this page: https://canada-ca.github.io/a11y/index.html

### Steps to reproduce

In fact it's all of these links that are supposed to link to something in OneDrive:
* [Designing for users on the autistic spectrum] (https://1drv.ms/b/s!AoQ9zmenRIM-cteCnzlfWn_euHc)
* [Design principles for users with cognitive disabilities] (https://1drv.ms/b/s!AoQ9zmenRIM-cMnlFpNqEkh4QVw)
* [Designing for users who are deaf or hard of hearing] (https://1drv.ms/b/s!AoQ9zmenRIM-bd8P0sewnmIoAyQ)
* [Designing for users with low vision] (https://1drv.ms/b/s!AoQ9zmenRIM-b9SC1Xmo2U3t298)
* [Designing for users with physical or motor disabilities] (https://1drv.ms/b/s!AoQ9zmenRIM-bjybecUWEZtmEmk)
* [Designing for users of screen readers] (https://1drv.ms/b/s!AoQ9zmenRIM-cbK4MTMrBWVWdBw)

### What is the expected *correct* behavior?

Is there a way to update the links to they're available to folks, right now there's a login screen.

cc @EricLavoie2

**Comment by shawnthompson** [comment]
@MaryBethBaker this site is a work in progress and those files are hosted on MS OneDrive.

We are looking for help fixing up the content, if you want to take a stab at it?

The plan is to have HTML first and from that page link to other formats like MS Docs and PDFs for people who would like to have a downloaded copy. 

You can get all the same information from https://ukhomeoffice.github.io/accessibility-posters/

**Comment by MaryBethBaker** [comment]
Hi @shawnthompson 

Thanks for the update and the link to the source material. I could submit a pull request for some basic html content, but I can't get to the content to validate it's exactly what is being pointed too. Do you have the posters in both official languages? Curious to know if you could add an alert at the top just letting folks know that this is still sort of an alpha page?

**Comment by shawnthompson** [comment]
@MaryBethBaker the alert is a great idea I think I'll try to do that sometime today. I'm trying to setup more time at work to put towards this project and start a "Task Force" with regular meetings. 

Feel free to open issues on any suggestions you have, we are open to anything right now.

I just got the documents from Share Services because I couldn't access them at ESDC either.

Stay tuned.

**Comment by DesignRight** [comment]
Hi, just wanted to let you know that this site is so very needed, thank you!!!
@shawnthompson - I may have met you. Do you or did you work for Roch L at one time? I was organizing the T716 course at CSPS that Roch was teaching and you may have been starting a new job.
@MaryBethBaker - the most recent versions of the posters (in both official languages) that I have seen are attached from DND. Slightly differently from the content in this site (the attached includes anxiety and dyslexia but does not include cognitive disabilities).
[JobAid_DesigningForAccessibility_DND20190531.pdf](https://github.com/canada-ca/a11y/files/5802230/JobAid_DesigningForAccessibility_DND20190531.pdf)
[JobAid_DesigningForAccessibility_DND20190531_FR.pdf](https://github.com/canada-ca/a11y/files/5802232/JobAid_DesigningForAccessibility_DND20190531_FR.pdf)

**Comment by shawnthompson** [comment]
@DesignRight I presently work for @rlambert27... I have taking the course and was asked to teach it but didn't have the bandwidth to add it to my schedule. 

I agree with you that this site is very much needed and we started another working group to work on it. We had our first meeting before th holidays and will be continuing pushing forward in 2021. If you'd like to join the meetings send me an email at work and I'll add you to the list. We'd love to have the help.

Hopefully in the next few weeks I'll be able to fix the broken links and start on this site.

Stay tuned and stay safe!

Oh and thanks @nschonni for the issue linking.

**Comment by DesignRight** [comment]
@shawnthompson - I am on the content side of course design but accessibility is big for me/us too. I will check with my manager about the working group and let you know. Maybe I could check content, etc. Thanks. 
@rlambert27 - hope all is well, it is Karen who used to take care of the content for T716 with George. Hope all is well with you! I'm back at the CRA now. So glad this site is happening.

**Comment by rlambert27** [comment]
@DesignRight Hey Karen! Glad to hear from you, really miss your work on the T716, it's kinda painful right now, haha!

We actually spoke about these posters the other day and I still don't understand why we don't point to the original content on Github (https://github.com/UKHomeOffice/posters/tree/master/accessibility/dos-donts). I don't see the purpose on hosting our own version of these files. We really should simply point to the original posters that are available in both French and English.

**Comment by DesignRight** [comment]
@rlambert27 - that's actually sad to hear about the T716, I guess they can't get anyone to update it. 
I agree, if you could point to the original content on Github without scaring people too much, that would be great. (Github can be a scary looking place.) And this Digital Accessibility Toolkit you are putting together will save every department from having their own versions. So very happy to see this!

**Comment by rlambert27** [comment]
All the credit for that goes to @shawnthompson as he is spearheading that task force! I agree though it's a great project and hopefully we can have lots of people participate to centralize a11y information!

**Comment by shawnthompson** [comment]
@rlambert27 feel free to put in your first PR into this project and change the links ;)

**Comment by shawnthompson** [comment]
Fixed! Thank you for your support!
