### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by DesignRight** [canada-ca/a11y#36]
On https://canada-ca.github.io/a11y/ 
The Printable posters (PDF format):  do not open, looks like a broken link, error message being recived.

<a id="das2" aria-labelledby="das2 das1" href="https://1drv.ms/b/s!AoQ9zmenRIM-cteCnzlfWn_euHc" rel="external">Designing for users on the autistic spectrum</a>

**Comment by nschonni** [comment]
Duplicate of #35
